@server_HostAddress = http://localhost:5011

###
POST {{server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "Alice"
}
###
POST {{server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "Alice"
}
###
GET {{server_HostAddress}}//api/auth/user
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhbGljZUBleGFtcGxlLmNvbSIsImV4cCI6MTc1NzU0MDE4NSwiaXNzIjoiQ2hhcnQtQ2hvaWNlIiwiYXVkIjoiQ2hhcnQtQ2hvaWNlLUF1ZGllbmNlIn0.o4VhUgpc9EgLn0LPikF7fa7bRtvQpw5OIaMp2ZJRF0hnXQxgeMNdh8PTE2340FgWtbeUyAwTFU1qK0u_3bT_yA

Accept: application/json
###
POST {{server_HostAddress}}//api/auth/refresh-token
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhbGljZUBleGFtcGxlLmNvbSIsImV4cCI6MTc1Nzc3MDIxMiwiaXNzIjoiQ2hhcnQtQ2hvaWNlIiwiYXVkIjoiQ2hhcnQtQ2hvaWNlLUF1ZGllbmNlIn0.-usIVBrcfsf7KgWkHpWy-QVTE_uzdpMXl_fsU5ja0wbr1mX5Ywp9UgvJQok32h-h5_UhlPuyurPelCKR4Ykr4g",
  "refreshToken": "OhlUg5hxOzYlChIZNNw0JdOobRD5YE4oZL9kh0T/yls="
}